### ISSUE TITLE
typograhpy.symbols.curly_quotes cannot be disabled in proselint/config

### ISSUE THREAD

**Issue by rpdelaney** [amperser/proselint#1086]
```console
$ proselint --version
0.10.2
$ cat $XDG_CONFIG_HOME/proselint/config
{
  "checks": {
    "typography.symbols.curly_quotes": false
  }
}
$ proselint README.md
README.md:15:12: typography.symbols.curly_quotes Use curly quotes “”, not straight quotes "". Found 10 times elsewhere.
README.md:17:17: typography.symbols.curly_quotes Use curly quotes “”, not straight quotes "".
$
```

**Comment by benknoble** [comment]
I have this issue too; I think you can disable *all* of `typography.symbols`, but it appears we can't get any more fine-grained.

I would suggest changing this issue or opening a new one that allows us to target individual checks and not just categories.

**Comment by rpdelaney** [comment]
Unfortunately, for my use case, not having a level of control over this error is a terminal deal breaker and I'm no longer using `proselint`. Therefore I can't check which other settings are also not working. If you (or anyone) opens an issue and references this one I'll be happy to close it.
