### ISSUE TITLE
Remove dependency on nose

### ISSUE THREAD

**Issue by mcepl** [amperser/proselint#1097]
I am a maintainer of Python packages in openSUSE, and I am on my crusade of eliminating nose1 from our distribution. When I look at its repository on https://github.com/nose-devs/nose, the last release 1.3.7 was on 2 Jun 2015, and even the last commit on the master branch was on 4 Mar 2016. Moreover, it seems nose won’t be running altogether with the upcoming releases of Python (3.9 or 3.10).

[This patch](https://github.com/amperser/proselint/files/5081162/remove_nose.patch.txt) eliminates dependency on nose, which has been unnecessary for a long time. There is none new dependency added because ``SkipTest`` exception is included in the standard library's ``unittest``.

**Comment by Nytelife26** [comment]
In the latest PR, #1134, this will be resolved anyway. Thank you for the contribution, though - rest assured, once proselint maintenance resumes, things will speed up around here again.

**Comment by Nytelife26** [comment]
Resolved in latest.
