### ISSUE TITLE
Is proselint still maintained?

### ISSUE THREAD

**Issue by carlsmedstad** [amperser/proselint#1140]
Hey :wave:

Last commit was three years ago. Is this project still maintained?

Is there anything one could do to help keep this project alive?

**Comment by carlsmedstad** [comment]
That's great to hear. Yes, I would!

**Comment by Nytelife26** [comment]
Side note: THe PR is #1134. Currently we're working on a merge for bringing the CI up to date and switching to python-poetry.

Any help you're willing to give after this would be appreciated. I'm sure @suchow would be happy to assign things, or we can co-ordinate the changes we know need to be made so far between us (the various issues, PRs, et cetera) - whatever your preferred method would be :)

**Comment by suchow** [comment]
Oops, @Nytelife26 is right, I cited the wrong PR.

@carlsmedstad we'll gratefully accept any help you're willing to offer.

**Comment by Nytelife26** [comment]
#1134 has been merged. I believe my next step is, following @suchow's lint fixes and fixing the PR, to triage our issues and pull requests so we can sort them properly and begin to work through community input.
