### ISSUE TITLE
Clear cache between pytest runs

### ISSUE THREAD

**Issue by suchow** [amperser/proselint#1151]
When trying to fix an issue with the uncomparables check, @Nytelife26 removed the memoization on that function, presumably  because the test suite was not passing even though the function was fixed. A better solution is for us to figure out how to get pytest to clear the cache/shelf between runs.

Here's the relevant memoization code:

https://github.com/amperser/proselint/blob/8a1cdc1492bf642196397caec9fe56e9fb521eb8/proselint/tools.py#L99

**Comment by Nytelife26** [comment]
This seems to be a culmination of various issues. I suspect I'll need to
take a further look through how the shelving system and the cache
dropping system works. I found an error not long ago with the
misplacement of an unbound variable in the memoize function so perhaps
there's more to this than it seems.

**Comment by Nytelife26** [comment]
I believe the cache system may need a redesign, or at the very least the package *should* clear the cache upon installation to avoid issues persisting between versions.

**Comment by joshmgrant** [comment]
If you need help with this task, I can pick it up or help. I wrote most of the original pytest tests.

**Comment by Nytelife26** [comment]
> If you need help with this task, I can pick it up or help. I wrote most
> of the original pytest tests.

I'd just like to say I greatly appreciate your volunteering and it's
awesome to see some of the original engineers still hanging around. You
can if you'd like to, any contributions are appreciated :)

**Comment by joshmgrant** [comment]
Just so I have the right context: was the issue with cache interfering with tests on local developer runs (eg on a laptop when someone is developing) or on GitHub Actions or both? I can add more logic if it's the latter case.

**Comment by Nytelife26** [comment]
GitHub Actions are fine since they are run in an individual environment each time, @joshmgrant. The issue lies with local environments on development machines since they do not clear the cache, and the user has to clear it manually.

The best solution to this is to reset the cache at the path on `~/.cache/proselint` in the installation script for proselint and also for test runs. Perhaps the test suite could disable memoization or use a cache bypass? Unsure.

**Comment by Nytelife26** [comment]
@joshmgrant was able to coordinate a solution by bypassing the cache altogether in test runs. This will be resolved soon.
