### ISSUE TITLE
KeyError in Python

### ISSUE THREAD

**Issue by oxytocin** [amperser/proselint#1240]
I installed proselint with pip. Running the example in the readme:
 
```py
import proselint
suggestions = proselint.tools.lint("This sentence is very unique")
```
gave me this output:

```
Traceback (most recent call last):
  File [path_removed], line 2, in <module>
    suggestions = proselint.tools.lint("This sentence is very unique")
  File "[path_removed]/venv/lib/python3.9/site-packages/proselint/tools.py", line 240, in lint
    checks = get_checks(config)
  File "[path_removed]/venv/lib/python3.9/site-packages/proselint/tools.py", line 142, in get_checks
    check_names = [key for (key, val) in options["checks"].items() if val]
KeyError: 'checks'
```

[The reason for this appears to be because the "lint" function makes "config" an empty dict by default](https://github.com/amperser/proselint/blob/f7faa720ea72cba3b0f7aa552fbf4dc62478e170/proselint/tools.py#L233). Perhaps having it load the default config instead would be a good solution?

I used Python 3.9.6 on MacOS 10.15.4 (Catalina). This is my first time submitting an issue, so let me know if I've done anything wrong.

**Comment by Nytelife26** [comment]
Thank you for the report. Making the config use the same defaults as the CLI would be a good solution.

**Comment by oxytocin** [comment]
Made a pull request (#1246)

**Comment by yishairasowsky** [comment]
@Nytelife26 @oxytocin @tommorris @fdb @blueyed 
I had the same problem as the original post. How do I load the default config? Thanks!
