### ISSUE TITLE
Add check for Mondegreens

### ISSUE THREAD

**Issue by suchow** [amperser/proselint#134]
http://www.amazon.com/Mondegreens-Book-Mishearings-Jacquie-Wines-ebook/dp/B007FRK69G/ref=sr_1_1?ie=UTF8&qid=1435244295&sr=8-1&keywords=mondegreen

(related to misquotes.)

**Comment by Decagon** [comment]
Closing since the `misc.mondegreens` module has been added.

**Comment by suchow** [comment]
Okay. I think it would be worthwhile to open a new issue that includes a link to that book, labelled `extraction`. We've fixed this issue by adding the rule, but it's far from complete.

**Comment by Decagon** [comment]
Sorry, I'm so used to merge-close that I closed this without thinking. Did you want to re-open this issue and just change the tag?
