### ISSUE TITLE
Useless dependency?

### ISSUE THREAD

**Issue by frenzymadness** [amperser/proselint#1352]
I see that this project depends on future:

https://github.com/amperser/proselint/blob/fe368030357a8300f383f9e906c08c73317d2021/pyproject.toml#L21

but I cannot find any real usage of this library here. Why do I care about it? future will no longer work with Python 3.12 because imp module has been removed from stdlib and the situation will be even worse with 3.13 because the lib2to3 which is the core of the future will be removed from stdlib as well.

**Comment by Nytelife26** [comment]
You do not have to justify why you might care about the existence of a useless dependency. The importance of compatibility and a tidy bundle size cannot be overstated. To the best of my knowledge, this dependency is residual from prior Python 2 support.

I am unsure of the direction @suchow would take with this, but realistically the ecosystem has long surpassed the need to continue supporting Python 2, and I cleaned up the project to remove all need for `future` a while ago. I would be in favour of removing it.

**Comment by Nytelife26** [comment]
Resolved passively in #1354.
