### ISSUE TITLE
Add rule on "use" vs. "utilize"

### ISSUE THREAD

**Issue by suchow** [amperser/proselint#162]
```
source:     DFW's dictionary notes in The Telegraph
source_url: http://bit.ly/1qudVuC
```

> Utilize
> A noxious puff-word. Since it does nothing that good old use doesn’t do, its extra letters and syllables don’t make a writer seem smarter; rather, using utilize makes you seem either like a pompous twit or like someone so insecure that she’ll use pointlessly big words in an attempt to look sophisticated. The same is true for the noun utilization, for vehicle as used for car, for residence as used for house, for presently, at present, at this time, and at the present time as used for now, and so on. What’s worth remembering about puff-words is something that good writing teachers spend a lot of time drumming into undergrads: “formal writing” does not mean gratuitously fancy writing; it means clean, clear, maximally considerate writing.

**Comment by Nytelife26** [comment]
This has been implemented since September 27th, 2015, via [c2aa786](https://github.com/amperser/proselint/commit/c2aa7861e96bb177b6468bb70c512a24e8874fcb).
