### ISSUE TITLE
Make `proselint .` run over entire directory, possibly with a recursive option

### ISSUE THREAD

**Issue by suchow** [amperser/proselint#292]

**Comment by michaelpacer** [comment]
Possibly including a recursive flag? It would seem that doing one would make the other fairly easy. I may be able to get to this next week.

**Comment by suchow** [comment]
Okay, what I'd like to do here is to match the convention of `jshint`, `pep8`, and others, where you run:

```
proselint .
```

and it runs over the whole directory. I tried implementing this by interpreting the `file` input arguments as Click Paths, but that didn't seem to work because I then had trouble opening the files.

@jstewmon, as our resident Click expert, would you be willing to take a look at this?

**Comment by jstewmon** [comment]
`jshint` and `pep8` operate on files with a particular extension - js and py, respectively. Does that constraint apply to proselint?

It seems to me that `proselint` may work on any type of text file that contains sentences, so would you expect that `proselint .` finds and checks all non-binary files?

You could defer the responsibility of answering the above questions to the user by updating the docs with examples of how to use `find | xargs` to supply the list of files to check. If you went that route, we would only need to change the printer to not strip the file path.

**Comment by suchow** [comment]
Okay, I created a first draft of this in PR #388. For now, it defines some limited set of file extensions (`.txt`, `.md`, `.rtf`, `.html`, `.tex`, `.markdown`) that get checked when you run `.proselint`. This will eventually be beefed up when proselint can detect the markup and turn off rules that false alarm on markup.

The `find | xargs` idea sounds good for now, though I'm unfamiliar with it, so I won't be able to update the docs myself until I learn more.

**Comment by suchow** [comment]
Closed by #388.
