### ISSUE TITLE
Website Lintscore Error

### ISSUE THREAD

**Issue by wordsmythe** [amperser/proselint#319]
http://proselint.com/lintscore/ 
Just needs some more parenthesis in the math. 

I think you mean the math expression to have the exponent (k) to apply to the whole thing, not just the part currently within the outer parenthesis. With F + T = 100, F = 10 (therefore T = 90), and k = 2, the statement comes out to 90*(0.9)^2. The exponent as it's written applies to just the 0.9, so you don't get 82.

**Comment by suchow** [comment]
The equation is correct as written: the lintscore is the number of true positives with a penalty term for false positives. Good catch though — the example is wrong and should be 72.9.

**Comment by suchow** [comment]
Fixed.
