### ISSUE TITLE
No args leads to repeated messages: Exception TypeError: "'NoneType' object is not callable" in ignore

### ISSUE THREAD

**Issue by ericpromislow** [amperser/proselint#323]
$ proselint --version
0.3.6
\# No args 
$ proselint 2>&1 | wc -l
305
$ proselint 2>&1 | grep 'in  ignored' |  wc -l
182

**Comment by michaelpacer** [comment]
Possibly related to https://github.com/amperser/proselint/issues/238.

**Comment by suchow** [comment]
I believe this has been fixed by #432. Let me know if it's still and issue and we can reopen.
