### ISSUE TITLE
Add tex support for vim plugin

### ISSUE THREAD

**Issue by JPFrancoia** [amperser/proselint#340]
Hi,

First, proselint is a wonderful piece of code. I find it very useful.

However, it lacks the support of tex files:

https://github.com/amperser/proselint/blob/master/plugins/vim/proselint.vim

Here you only support text files, but tex files would be great too (because you often write prose in LaTex).

Changing text to tex in all the fille works, but it would be great to add it to proselint in a proper way.

**Comment by lcd047** [comment]
The _proper_ way to do this is pretty complicated, and there are a few other things to fix about that particular piece of code first.  I might consider posting a PR later, if #355 gets solved.
