### ISSUE TITLE
Config files are loaded only from a central location

### ISSUE THREAD

**Issue by lcd047** [amperser/proselint#356]
The `.proselintrc` file is [searched for](https://github.com/amperser/proselint/blob/master/proselint/command_line.py#L56) only in the base directory of proselinty itself.  This makes it impossible for the user to disable some of the checking rules.

**Comment by blueyed** [comment]
By now it also looks at `~/.proselintrc` (related https://github.com/amperser/proselint/issues/747), but still supports no custom (via args) or project-based (by looking upwards from the file being linted) config.

**Comment by dialex** [comment]
Exactly what @blueyed said. I expected that `proselint` would look for the config file at the root folder of my project, not my entire system! Passing the config filepath (via args) would also do the trick, but it's also impossible.
I want to run this tool on Travis, so... I don't think this is feasible 😢
