### ISSUE TITLE
explain corpora directory

### ISSUE THREAD

**Issue by alaska** [amperser/proselint#357]
It looks to me as if this is part of your testing suite (makes sense), and it also makes sense that you wouldn't duplicate them in the repo (as you say), but that directory's purpose is mysterious unless you look at the code.  I might still have it wrong, myself.

I would add a bit to the README.md detailing what that directory is for, what you'd normally put there, and why it's empty.

**Comment by laraross** [comment]
Thanks for the suggestion, I'll add the description from http://proselint.com/corpus to the readme.
