### ISSUE TITLE
Create plugin for Atom editor

### ISSUE THREAD

**Issue by suchow** [amperser/proselint#36]

**Comment by jenskanis** [comment]
@suchow are you still actively working on a `proselint` Atom plugin? I'd love to use it!

Thanks,
Jens

**Comment by smockle** [comment]
I just published my initial attempt at displaying `proselint` results in Atom Editor, using the atom-linter API: https://atom.io/packages/linter-proselint. Feedback welcome!

**Comment by suchow** [comment]
Just tried it out, and it works! That's great.

I'm not sure what's the best way to organize plugins and keep track of them. Maybe we can make a plugins section in the README with links to all the available plugins. So far, we've been placing the plugins directly in https://github.com/amperser/proselint/tree/master/plugins. If you have any thoughts, I'd love to hear them.

**Comment by smockle** [comment]
@suchow Awesome, thank you for testing! :) Adding a section to the README sounds like a good, extensible way to maintain a list of text editor plugins. The Oceanic Next color scheme does that: https://github.com/voronianski/oceanic-next-color-scheme#other-editors; I think I’ve seen such lists elsewhere too.

**Comment by jenskanis** [comment]
Awesome, this is amazing. I had some trouble installing it because I didn't have Atom's Linter package installed by default, might be worth mentioning in the README. Good job!

**Comment by suchow** [comment]
@smockle I'm going to close this issue because I think you've succeeded. Thanks for your contribution!
