### ISSUE TITLE
Assorted issues from Debian mailing list

### ISSUE THREAD

**Issue by suchow** [amperser/proselint#389]
I found this discussion online:

https://www.mail-archive.com/debian-bugs-dist@lists.debian.org/msg1402747.html

**Comment by viccuad** [comment]
Hi, Debian maintainer here (future one, when proselint passes sanity checks).

I have already fixed some of the simple ones, and reported the remaining ones: #345, #395, #414, #415, #416.

In case anyone wants to follow the discussion there, you can use this [link](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=816192)

**Comment by suchow** [comment]
@viccuad Thanks for your help, it's much appreciated. Yes, seems right to close it — let's continue the conversation on an issue-by-issue basis. I look forward to improving `proselint` and its integration with Debian with you.
