### ISSUE TITLE
Validity of Strunk & White as source

### ISSUE THREAD

**Issue by hughgrigg** [amperser/proselint#394]
I feel obliged to point this out: http://chronicle.com/article/50-Years-of-Stupid-Grammar/25497

If we accept Pullum's criticisms there then it may be better to not mention Strunk and White as authorities in the documentation.

**Comment by suchow** [comment]
When you speak of Strunk & White being mentioned as authorities, are you referring to the line of http://proselint.com/ that says "But poring over Strunk & White hardly makes one a better writer — it turns you into neither Strunk nor White."?

**Comment by hughgrigg** [comment]
Yes, and also "You’ll be guided by advice inspired by Bryan Garner, David Foster Wallace, Chuck Palahniuk, Steve Pinker, Mary Norris, Mark Twain, Elmore Leonard, George Orwell, Matthew Butterick, William Strunk, E.B. White..."

**Comment by suchow** [comment]
I think the sentence I quoted above hedges sufficiently by saying that reading the book hardly makes you a better writer. 

I'm sure we can find *something* valuable there, though yes, we should take into account Pullum's caveats (more at http://www.lel.ed.ac.uk/~gpullum/LandOfTheFree.html). I'll make note of this in the relevant issue (#8).

**Comment by hughgrigg** [comment]
Sure, sounds good. Just felt this was worth mentioning.
