### ISSUE TITLE
Remove `shell=True` as they are a security hazard

### ISSUE THREAD

**Issue by viccuad** [amperser/proselint#395]
Hi, 

As said on [Python's subprocess docs](https://docs.python.org/2/library/subprocess.html), using shell=True can be a [security hazard](https://docs.python.org/2/library/subprocess.html#frequently-used-arguments), as they open the door to shell code injection. 

`shell=True` could for example be removed from:
```
out = subprocess.check_output("proselint --version", shell=True)
subprocess.call("proselint --debug >/dev/null", shell=True)
```
These other examples are possibly vulnerable to shell code injection:
```
out = subprocess.check_output("proselint {}".format(fullpath), shell=True)
subprocess.call("{} {}".format("open", fullpath), shell=True)
subprocess.call("proselint {} >/dev/null".format(filepath), shell=True)
```
These other examples could maybe use python equivalents instead?:

```
subprocess.call("find . -name '*.pyc' -delete", shell=True)
subprocess.call("rm -rfv proselint/cache > /dev/null && mkdir -p
{}".format(os.path.join(os.path.expanduser("~"), ".proselint")),
shell=True)

```

Since using `shell=True` can be potentially dangerous even when if it is safe where used in Proselint, you might want to review all of its uses and issue some [security advisories](http://oss-security.openwall.org/wiki/disclosure/cve) if they were to be a problem.

Also, forking subprocesses is more expensive than handling it in Python, and if Proselint removes it, the [Process Identifier Preservation Society ](http://bonedaddy.net/pabs3/log/2014/02/17/pid-preservation-society/) will thank you :).

Cheers.

**Comment by suchow** [comment]
Okay, I've removed all the instances of `shell=True`.

I don't know how to convert the last block into native Python commands.
