### ISSUE TITLE
'bug' when run with op to terminal?

### ISSUE THREAD

**Issue by dpawson** [amperser/proselint#405]
Ran on a pymarkdown file. Worked... then appended hundreds of lines 
Exception TypeError: "'NoneType' object is not callable" in  ignored

at the end. run using 
proselint notes.md >res.txt
and the 'oddity' does not show?

**Comment by suchow** [comment]
Yes, thanks, this is a known bug (#238). 

If you have any thoughts, we could use help!

**Comment by dpawson** [comment]
thanks. I used to think software was predictable!
182 'extra' lines... Perhaps there is a max count somewhere, after which no more errors are reported?

My only other thought is that it's in a recursion, the 182 errors are unwinding the stack?

Sorry not to help  further?
