### ISSUE TITLE
Fix PEP8 style issues

### ISSUE THREAD

**Issue by viccuad** [amperser/proselint#416]
By using `check-all-the-things` package from Debian, one can find a lot of PEP8 style issues.

```
$ find -type f -iname '*.py' -exec pep8 --ignore W191 {} +
./proselint/tools.py:211:41: E226 missing whitespace around arithmetic operator
./proselint/tools.py:211:46: E226 missing whitespace around arithmetic operator
./proselint/checks/leonard/exclamation.py:41:17: E226 missing whitespace around arithmetic operator
./proselint/checks/leonard/exclamation.py:45:26: E226 missing whitespace around arithmetic operator
./proselint/checks/garner/many_a.py:26:22: E241 multiple spaces after ','
./proselint/checks/garner/many_a.py:27:28: E241 multiple spaces after ','
./proselint/checks/garner/many_a.py:28:23: E241 multiple spaces after ','
(and ~500 more)
```

**Comment by suchow** [comment]
I'm confused — we run the `pep8` linter automatically using Travis, and when I run the linter over the codebase locally, I get no errors:

```
❯ pep8 --version
1.7.0

proselint git/master
❯ pep8 .
```

**Comment by suchow** [comment]
Oh, I figured it out. `pep8` excludes E121, E123, E126, E226, E24, and E704 by default.

**Comment by suchow** [comment]
This is an interesting problem. `pep8` ignores those rules because "they are not rules unanimously accepted, and PEP 8 does not enforce them"? Because the creator does not endorse those checks, I think we should keep this as it is. Maybe a patch to Debian's `check-all-the-things` is appropriate.

**Comment by viccuad** [comment]
`check-all-the-things`' pep8 is also 1.7.0 (the `--ignore` flag gets us those messages).

All but 4 of the messages are E241, adding multiple spaces to square the lists on checks. I'm perfectly happy closing this.
