### ISSUE TITLE
Wow

### ISSUE THREAD

**Issue by suchow** [amperser/proselint#435]
http://www.serenity-software.com/pages/comparisons.html

**Comment by suchow** [comment]
I played with this today, running it over Lauren Collin's New Yorker article "Love App". Oh my.

**Comment by michaelpacer** [comment]
This part is crucial

Writers are pleased when a grammar checker finds mistakes in their work,
and most checkers do that.  *But what writers don’t know is how often the
checker (1) overlooks common or obvious mistakes, (2) falsely flags correct
expressions as mistakes, and (3) offers, as "corrections," new mistakes.*  The
only way to discover that information and answer these three crucial
questions is by *direct comparison of their performances*.
