### ISSUE TITLE
sort output by line number?

### ISSUE THREAD

**Issue by denispelli** [amperser/proselint#505]
The output in my BBEdit results window is helpful and readable, but would be much easier to use if it were sorted by line number. here's an example:

~/Dropbox/legibility/Legibility87.txt:1339: after_the_deadline.redundancy Redundancy. Use 'bit' instead of 'tiny bit'.
~/Dropbox/legibility/Legibility87.txt:60: after_the_deadline.redundancy Redundancy. Use 'feelings' instead of 'inner feelings.'.
~/Dropbox/legibility/Legibility87.txt:1124: cliches.garner 'first and foremost,' is cliché.
~/Dropbox/legibility/Legibility87.txt:52: consistency.spacing Inconsistent spacing after period (1 vs. 2 spaces).
~/Dropbox/legibility/Legibility87.txt:57: consistency.spacing Inconsistent spacing after period (1 vs. 2 spaces).

**Comment by suchow** [comment]
Good suggestion, @vikasgorur has implemented it (#512) and it will be available in the next release.

**Comment by denispelli** [comment]
thanks!


[image: photo]
*Denis Pelli*
Professor of Psychology & Neural Science, New York University
+1-646-258-7524 | denis.pelli@nyu.edu | http://psych.nyu.edu/pelli/ | Skype:
denispelli <#> | http://denispelli.com
<http://www.facebook.com/denispelli>
