### ISSUE TITLE
How to install proselint plugin on Emacs

### ISSUE THREAD

**Issue by sbacelar** [amperser/proselint#527]
I have installed `proselint` and it works on the terminal. But when I try to include `proselint` plugin code on my `init.el` Emacs does not initialise. Is it possible to give some guidance about the installation process?

**Comment by michaelpacer** [comment]
I think based on a conversation with @asmeurer that we may need to work on our emacs/flycheck integration. I don't use emacs or know its extension language, but when it is now a priority.

**Comment by mavit** [comment]
One needs to `(require 'flycheck)` before evaluating the (current) contents of [`flycheck-proselint.el`](https://github.com/amperser/proselint/blob/master/plugins/flycheck/flycheck-proselint.el).

The ideal situation is probably for the Emacs plugin to be [packaged](/melpa/melpa#recipe-format) and pushed to [MELPA](https://melpa.org/).  I hope to find time to look at this.
