### ISSUE TITLE
Add Instructions for Running Automated Tests on README

### ISSUE THREAD

**Issue by joshmgrant** [amperser/proselint#575]
It might be helpful to include some instructions on the README for running the automated tests located in `tests/`. It would include: 

- the command for running all tests via Bash using all supported versions of Python
- description of how the tests are used on CI (TravisCI and Appveyor)

I use [py.test](https://pypi.python.org/pypi/pytest) for running the tests, but CI uses nose. They're mostly compatible but we can standardize on using nose. Should anything else be included? 

I'm happy to submit the changes myself.

**Comment by suchow** [comment]
Closed by #582.
