### ISSUE TITLE
False alarm: `not-so-hotly-contested`

### ISSUE THREAD

**Issue by cpitclaudel** [amperser/proselint#603]
The exception to the `ly` rule mentioned by by Garner doesn't seem to be implemented: `not-so-hotly-contested race` is flagged as `garner.phrasal_adjectives.ly No hyphen is necessary in phrasal adjectives with an adverb ending in -ly`.

**Comment by j10sanders** [comment]
Thanks for finding this false positive, @cpitclaudel 

I've made a pull request to fix it here: https://github.com/amperser/proselint/pull/632
