### ISSUE TITLE
Support for Visual Studio Code

### ISSUE THREAD

**Issue by ppeszko** [amperser/proselint#608]
First of all, thank you for the great work @suchow ♥️🙇

I was missing a support of proselint in Visual Studio Code. So I though instead of complaining I will do it myself 😁 If somebody is interested here it is: https://github.com/ppeszko/vscode-proselint It just a beginning but it's functional. 

Cheers!

**Comment by suchow** [comment]
Thanks, Patryk! 🎉

I'll add your plugin to the list in the README, which I hope will improve its visibility for Visual Studio Code users.

**Comment by joshmgrant** [comment]
@ppeszko This is great! I also use VS Code so I'm glad to see someone do this. Thanks so much!
