### ISSUE TITLE
"Cash money" isn't necessarily redundancy

### ISSUE THREAD

**Issue by tommorris** [amperser/proselint#665]
Example:

> [product name] is well worth buying despite costing cash money.

Proselint flagged this up as an error. I'm not sure it is. It isn't formal standard English, but not everything one writes has to be. It is a use of slang for emphasis. I'm not sure whether this should be fixed, but it might be worth considering whether it is a problem or not.

**Comment by adammichaelwood** [comment]
one assumes any variety of slang would trigger lots of checks in any good style guide.

**Comment by Nytelife26** [comment]
It is a redundancy, though. Cash and money are the same. Cash is not a specific variant of money, unless you take the definition to mean tangible currency - in which case, you would simply use the term "cash".
