### ISSUE TITLE
Is the only way to get this via pip?

### ISSUE THREAD

**Issue by jeffstokes72** [amperser/proselint#679]
I note there are no other instructions. And no explanation of what pip is. Maybe a link to pip for someone who doesn't have it would be good?

**Comment by thari** [comment]
I installed it using Homebrew in Mac

**Comment by mavit** [comment]
FWIW, there are unofficial packages for [Fedora](https://getfedora.org/) at https://copr.fedorainfracloud.org/coprs/mavit/python-proselint/.
