### ISSUE TITLE
custom `.proselintrc` path

### ISSUE THREAD

**Issue by netflash** [amperser/proselint#702]
Is there a way to point a custom path for the `.proselintrc` ? e.g. `$(pwd)`.

If not - I can try to implement it.

**Comment by ankita240796** [comment]
Also, there should be a mechanism to add custom checks to Proselint. If @netflash is not working on this, I would like to take this issue.

**Comment by netflash** [comment]
@ankita240796 please go ahead, as I can't find time for it.

**Comment by ankita240796** [comment]
Sure! Thanks

**Comment by Nytelife26** [comment]
This was resolved in #1081.
