### ISSUE TITLE
Please use XDG paths for config and cache

### ISSUE THREAD

**Issue by z0rc** [amperser/proselint#747]
The [XDG Base Dir Spec](https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html) is more than a decade old. It's discouraged to put app's configuration and cache in user's home. Please use shell envs `$XDG_CACHE_HOME` (fallback to `$HOME/.cache` if not set)  and `$XDG_CONFIG_HOME` (fallback to `$HOME/.config` if not set).

It's worth mentioning that this spec applies to cli tools too. For example git, systemd, htop, mc and many others honor it.

Please keep our homes clean, thanks!

**Comment by suchow** [comment]
@z0rc Thanks for the suggestion — would you be interested & willing to open a PR with this change?
