### ISSUE TITLE
Tests missing from pypi.org

### ISSUE THREAD

**Issue by mavit** [amperser/proselint#867]
The [0.10.0 source tarball hosted on pypi.org](https://files.pythonhosted.org/packages/ed/84/d2adefc48e8cf4d8c385cd39d68c9ff67a714a0a95b5ee25e6c7c4448bf0/proselint-0.10.0.tar.gz) is different from the [0.10.0 source tarball hosted on github.com](https://github.com/amperser/proselint/archive/0.10.0.tar.gz), and is missing the tests.

**Comment by joshmgrant** [comment]
@mavit This is correct. During a build using setup.py, the test packages are excluded (see https://github.com/amperser/proselint/blob/master/setup.py#L41). This was done to reduce the tarball size and maintain efficiency.

Would you like to have the tests included in the PyPI tarball?

**Comment by mavit** [comment]
I maintain the Proselint package for Fedora.  We need the tests for two reasons: 

- We run the tests at package build time to check everything is working as expected, and then [periodically as Proselint’s dependencies are updated within the distribution](https://apps.fedoraproject.org/koschei/package/proselint).
- If a project's upstream was to disappear over night, we’d want to have everything required in case someone wished to set up their own fork of the project, so that we could continue to distribute it.

Now, it’s not a problem for me to fetch the tarball from GitHub rather than from PyPI.  However, it does seem confusing that two different source tarballs should exist with undocumented differences.

**Comment by joshmgrant** [comment]
Thanks for this! This is helpful information, and it sounds like my (I think it was my) initial idea of excluding tests from distributions was short-sighted.

If there's no objections from @suchow I'll open a PR to add back the test packages.

**Comment by suchow** [comment]
@mavit Is 0.10.0 the first time this has happened? I changed a setting in the build process that went awry and needed to upload the package to PyPI by hand. I'll try releasing 0.10.1 and see if it's fixed.

**Comment by suchow** [comment]
@mavit Okay, release 0.10.1 and the PyPI uploading worked: https://pypi.org/project/proselint/. Does 0.10.1 have this issue?

**Comment by viccuad** [comment]
Hello,

Maintainer of the Debian package chiming in, the PyPI 0.10.1 keeps missing `tests/*` (but not `test/illegal-chars.txt`, as it was added manually to the `MANIFEST.in`).

On our side we have the same conundrum, we would like to have the tests shipped as part of
the source distribution, as:
- they get run on build time
- they [get run when proselint's dependencies get updated within the distribution](https://ci.debian.net/packages/p/python3-proselint/unstable/amd64/), informing us of dependencies breaking ABI/API and therefore breaking proselint
- They are part of the source, needed for contributing and doing TDD, and for archival purposes

The shipped tarballs from github are indeed nice for some people, but we don't use them in this case, to perform sanity checks (and try to contribute back) against what people get from `pip`.

**Comment by suchow** [comment]
@viccuad Thanks, is this a new issue or have we never shipped the tests? If we haven't, do you know what we need to do?

**Comment by mavit** [comment]
Before 0.9.0: The tests are included in the tarballs but are installed at build time, so we [delete them as we build an RPM package](https://src.fedoraproject.org/rpms/proselint/blob/4ab876af12b65b9b040b44f4464b6905a1005099/f/proselint.spec#_54).
0.9.0: The tests are included in the [tarball](https://files.pythonhosted.org/packages/source/p/proselint/proselint-0.9.0.tar.gz) and are not installed.
After 0.9.0: The tests are not included in the tarballs.

**Comment by suchow** [comment]
@mavit @viccuad Do you think adding `tests/*` to MANIFEST.in will do the trick?

**Comment by mavit** [comment]
> Do you think adding `tests/*` to MANIFEST.in will do the trick?

Running `python ./setup.py sdist` shows that it does, except we need to be a bit more careful with the wildcard, because we don't want to include any `.pyc` files.

I have raised pull request #871 for this.

**Comment by suchow** [comment]
I'll release 0.10.2 with the changes from #871. Let's see if that fixes things.

**Comment by suchow** [comment]
0.10.2 has been released. I believe it solves this issue.

**Comment by mavit** [comment]
It does.  Thanks.
