### ISSUE TITLE
Upgrade to click>=7.0

### ISSUE THREAD

**Issue by shivank1234** [amperser/proselint#924]
Using latest version of click package would help in functioning of other repo's who uses proselint as a dependency.

**Comment by carlsmedstad** [comment]
This could be closed. @Nytelife26 @suchow

**Comment by Nytelife26** [comment]
@carlsmedstad I greatly appreciate your help triaging these :)

**Comment by carlsmedstad** [comment]
@Nytelife26 You're welcome! Will continue to drop by when I have time a see where I can be of use :)

**Comment by suchow** [comment]
@carlsmedstad thank you!
